### PR TITLE
backoff increase

### PR DESCRIPTION
**Pull request by YiannisGkoufas**
Addresses #57

### CODE REVIEW

**Comment by YiannisGkoufas** [comment]
Make sure that we test it without having a provisioner working and then bring it up.
Also add logging to indicate that the client retries to connect.

**Comment by YiannisGkoufas** [comment]
@wlan0 following up on our discussion about logging the retries, I believe it might not be as easy as I thought. at least until https://github.com/grpc-ecosystem/go-grpc-middleware/issues/356 is merged maybe? let me know if I missed something

**Review by wlan0 — APPROVED** [review]

**Pull request merged**
