### PR TITLE
Add Deployment documentation

### PR DESCRIPTION
**Pull request by mengjiao-liu**
Add Deployment documentation

Ref #32

### CODE REVIEW

**Comment by wlan0** [comment]
@mengjiao-liu all apologies for my delay in responding! Is this PR meant to support/augment this document? https://github.com/kubernetes-sigs/container-object-storage-interface-api/blob/master/docs/deployment-guide.md

**Comment by mengjiao-liu** [comment]
> @mengjiao-liu all apologies for my delay in responding! Is this PR meant to support/augment this document? https://github.com/kubernetes-sigs/container-object-storage-interface-api/blob/master/docs/deployment-guide.md

Corresponding to this issue #32

**Pull request merged**
